language: cpp
env:
  matrix:
  - ARCH=
  - ARCH=rpi
  global:
    - secure: "JGkLKSaVlkQ/D4hHoXEmbHrSzhGus60NLZ+jscvqS0tuwxwot1EMsi++YLaNNZjNSojXHmWd1A3Hu1276E/bKJ6XIXnDEIRmuuOfWfB5BGCIXAVzigC7cpltRwZyhqgRqRCbOqUMY7/sGnlT5zGOMQUm/F8UPb6DAnY+ZBZrr2s="

  os:
  - linux
  - osx

matrix:
  exclude:
   - os: osx
     env: ARCH=rpi

before_install:
- "./script/depinstall.sh"

script:
- "./script/build.sh"

after_success:
- "./script/deploy-git.sh"

addons:
  coverity_scan:
    project:
      name: jamoma/JamomaPureData
      description: Build submitted via Travis CI
    notification_email: jamoma-devel@lists.sourceforge.net
    build_command_prepend: "cmake .. -DBUILD_JAMOMAPD=ON -DBUILD_JAMOMAMAX=OFF; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
