language: cpp
env:
  matrix:
  - ARCH=
  - ARCH=i386
os:
  - linux
#  - osx

branches:
  only:
    - feature/travis-build

before_install:
- "./script/depinstall.sh"

script:
- "./script/build.sh"

after_success:
- "./script/deploy-git.sh"