language: cpp
env:
  matrix:
  - ARCH=
  - ARCH=rpi
  - ARCH=mingw-64
  global:
  - secure: JGkLKSaVlkQ/D4hHoXEmbHrSzhGus60NLZ+jscvqS0tuwxwot1EMsi++YLaNNZjNSojXHmWd1A3Hu1276E/bKJ6XIXnDEIRmuuOfWfB5BGCIXAVzigC7cpltRwZyhqgRqRCbOqUMY7/sGnlT5zGOMQUm/F8UPb6DAnY+ZBZrr2s=
  - secure: ancOGXIF6jHoV/fX94ox9ASy9Q4f3OHSB2YojQoekHjwrWeCMfgdED1pM/OJyWQGbODmoPZHVOggjiHGuoOz8gJh+xVKz5t6n32hsD9aCsBwYt86/pOANTK5zISy1QUDmC9ojuCQsgi7N4/9M/621ZsIwpqGsTP5uoqHsOvAvII=
  os:
  - linux
  - osx

matrix:
  exclude:
  - os: osx
    env: ARCH=rpi
  - os: osx
    env: ARCH=mingw-64
  allow_failures:
   - os: linux
     env: ARCH=mingw-64

before_install:
- "./script/depinstall.sh"

script:
- "./script/build.sh"

after_success:
- "./script/deploy-git.sh"

addons:
  coverity_scan:
    project:
      name: jamoma/JamomaPureData
      description: Build submitted via Travis CI
    notification_email: jamoma-devel@lists.sourceforge.net
    build_command_prepend: "mkdir build && cd build && /tmp/cmake/bin/cmake .. -DBUILD_JAMOMAPD=ON -DBUILD_JAMOMAMAX=OFF; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
