language: cpp
env:
  matrix:
  - ARCH=
  - ARCH=rpi
  global:
  - secure: JGkLKSaVlkQ/D4hHoXEmbHrSzhGus60NLZ+jscvqS0tuwxwot1EMsi++YLaNNZjNSojXHmWd1A3Hu1276E/bKJ6XIXnDEIRmuuOfWfB5BGCIXAVzigC7cpltRwZyhqgRqRCbOqUMY7/sGnlT5zGOMQUm/F8UPb6DAnY+ZBZrr2s=
  - secure: CT+JN/eRbQuMmiQH/wfwcMXSDNDkwGGBOjRlocUYCh1mvrOF6v/+gQ6cq+QK7mzci7XUlWbVCurA94c8EGvVYDnOvzCxmmS5f3zU4AVd19A2DxqiHfSqqYIC3NTm4GNiy9t9lgm/hVyj3wsBmQS9p1bLAcguYN99GMepXKiioEU=
  os:
  - linux
  - osx

matrix:
  exclude:
  - os: osx
    env: ARCH=rpi

before_install:
- "./script/depinstall.sh"

script:
- "./script/build.sh"

after_success:
- "./script/deploy-git.sh"

addons:
  coverity_scan:
    project:
      name: jamoma/JamomaPureData
      description: Build submitted via Travis CI
    notification_email: jamoma-devel@lists.sourceforge.net
    build_command_prepend: "mkdir build && cd build && /tmp/cmake/bin/cmake .. -DBUILD_JAMOMAPD=ON -DBUILD_JAMOMAMAX=OFF; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
